// SPDX-License-Identifier: GPL-3.0
/*
    Auto-generated by snarkJS (https://github.com/iden3/snarkjs)
    for the ConfidentialTransfer v2 circuit.

    Circuit: confidential_transfer.circom
    Proving system: Groth16 on BN254 (alt_bn128)
    Public inputs: 6 (three BabyJubJub commitment points × 2 coordinates)
    Constraints: 7,975 (7,670 non-linear + 305 linear)

    Deployed at: 0x70FA331534619DBd4051b22b7fb19e647be141b0 (Flow EVM testnet)
    Deploy tx:   4bd009caa17e774d95fcb9ffd0c13cf16191fee390a6578bf1b9b49f4c0b02f9

    ABI selector: verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[6]) = 0xf398789b

    Trusted setup:
    - Phase 1: Hermez Powers of Tau (pot28, multi-party ceremony)
    - Phase 2: Single contributor (EXPERIMENTAL — not for production)

    IMPORTANT: pi_b swap required — see @openjanus/groth16 SDK or research/PIB_SWAP.md
*/

pragma solidity >=0.7.0 <0.9.0;

contract Groth16Verifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data (circuit-specific — ConfidentialTransfer v2)
    uint256 constant alphax  = 20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 constant alphay  = 9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 constant betax1  = 4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 constant betax2  = 6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 constant betay1  = 21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 constant betay2  = 10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 5712475676734462576700382460765152003854087185438078166401637335648250934395;
    uint256 constant deltax2 = 16692691284393527361719794261711007484727031362304868294622409056386462511592;
    uint256 constant deltay1 = 9121735090315638299375999378635036853680331988772000475953596992548647534650;
    uint256 constant deltay2 = 1045685963477311191699699792198480614109994746845458942972787041628648922361;

    uint256 constant IC0x = 12948445108808748428189526759330739138352043307625425417208296849448999008399;
    uint256 constant IC0y = 2613345065213488826650537223444746492402234294965124030976103235725654491975;

    uint256 constant IC1x = 3991979182682126130118555686543280892052641789862834068051709528016702619779;
    uint256 constant IC1y = 461987071043965790673153978800186112259185305857570265098988624221522320686;

    uint256 constant IC2x = 4903088920808035796677378882113849012807340941759160020859845343872838816662;
    uint256 constant IC2y = 3136700987628562276992844365468886018084214489115350492139865302103667366600;

    uint256 constant IC3x = 14185588829856838345443309122134315424034191919293438167793385930148575296140;
    uint256 constant IC3y = 3945057627302775849371713659409059459375524882516905862310471344640065579826;

    uint256 constant IC4x = 15209726686673343940363884576288527778273933943409965499689478405366287959650;
    uint256 constant IC4y = 11417679503958955785765026191977462619262567638034294073231727171867638105325;

    uint256 constant IC5x = 5548481606561060796876138783026913693814476636073137530219939214739431312535;
    uint256 constant IC5y = 10397992345974610291729028599551046128155792182203573654126503797824757218550;

    uint256 constant IC6x = 14776394224770445097025204607777408750692776950540224040594650343209311966255;
    uint256 constant IC6y = 2676777791480983579385423004767007871470879009256239654872533852293401337222;

    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;
    uint16 constant pLastMem = 896;

    /**
     * @notice Verify a ConfidentialTransfer Groth16 proof.
     *
     * @param _pA  G1 point pi_a
     * @param _pB  G2 point pi_b — Fp2 coords SWAPPED vs snarkjs output (imaginary, real order)
     * @param _pC  G1 point pi_c
     * @param _pubSignals  6 public signals:
     *   [0] old_commit.x, [1] old_commit.y
     *   [2] transfer_commit.x, [3] transfer_commit.y
     *   [4] new_commit.x, [5] new_commit.y
     * @return bool  true if the proof is valid
     */
    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[6] calldata _pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x
                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all public signals are in the scalar field
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))
            checkField(calldataload(add(_pubSignals, 160)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
